### PR TITLE
fix: unable to enter data with spaces in prompts

### PR DESCRIPTION
**Pull request by laqda**
proposal fix #514

### CODE REVIEW

**Comment by c4spar** [comment]
Thx @laqda for the fix!
I think this solution should be fine. If you remove the draft status i can merge the PR.

**Comment by laqda** [comment]
> Thx @laqda for the fix! I think this solution should be fine. If you open a PR i can merge it.

Done ✅

**Comment by c4spar** [comment]
@laqda you need to open the pr to the main branch of the cliffy repo. you opened a PR to your own repo 😉

**Comment by laqda** [comment]
> @laqda you need to open the pr to the main branch of the cliffy repo. you opened a PR to your own repo 😉

Sorry I am doing that from my phone, I do not have my computer 😅

**Pull request closed without merging**
